version: '1.3.0.{build}-{branch}'
before_build:
- cmd: dotnet restore
build:
  publish_nuget: true
after_build:
- dotnet pack "src\Narochno.Slack\project.json" -c Release
artifacts:
- path: src\Narochno.Slack\bin\Release\*.nupkg
deploy:
- provider: Environment
  name: nuget.org
  on:
    branch: master